authentication/urls.py
from django.urls import path
from authentication.views import show_landing, login, logout, register

app_name = 'authentication'

urlpatterns = [
    path('', show_landing, name='show_landing'),
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),  
]

langganan/urls.py
from django.urls import path
from django.views.generic import TemplateView
from langganan import views

app_name = "langganan"

urlpatterns = [
    path('', views.langganan, name='langganan'),
    path('beli_paket/', views.beli_paket, name='beli_paket'),
    path('daftar_kontributor/', views.daftar_kontributor, name='daftar_kontributor')
]
    

main/urls.py
from django.urls import path
from main.views import show_main

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
]

pacilflix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('', include('main.urls')),
    path('', include('authentication.urls')),
    path('admin/', admin.site.urls),
    path('tayangan/', include('tayangan.urls')),
    path('trailer/', include('trailer.urls')),
    path('ulasan/', include('ulasan.urls')),
    path('langganan/', include('langganan.urls')),
    path('daftar_favorit/', include('daftar_favorit.urls', namespace='daftar_favorit')),
    path('daftar_unduhan/', include('daftar_unduhan.urls', namespace='daftar_unduhan')),
]

tayangan/urls.py
# from tayangan.views import show_tayangan # Hapus baris ini atau komentari
from django.urls import path
from django.views.generic import TemplateView
from .views import *

app_name = 'tayangan'

urlpatterns = [
    path('series/episode/<series_id>/<episode_number>/', episode, name='episode'),
    path('film/<film_id>/', film, name='film'),
    path('series/<series_id>/', series, name='series'),
    path('', tayangan, name='tayangan'),
    path('unduh_tayangan/<str:id_tayangan>/', unduh_tayangan, name='unduh_tayangan'),
    path('unduh_tayangan_series/<str:id_tayangan>/', unduh_tayangan_series, name='unduh_tayangan_series'),
    path('insert_favorit_film/<str:id_tayangan>', tambah_ke_daftar_favorit, name='insert_favorit'),
    path('insert_favorit_series/<str:id_series>/<str:judul>/', daftar_favorit_series, name='insert_favorit_series'),
    path('add_tonton/', add_tonton, name='add_tonton'),
    path('ulasan/<tayangan_id>', open_ulasan, name='open_ulasan'),
    path('search/', show_hasil_pencarian_tayangan, name='hasil_search'),
]

trailer/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import *


app_name = 'trailer'

urlpatterns = [
    path('search-trailer/', show_hasil_pencarian_trailer, name='search_trailer'),
    path('trailer-guest/', trailer_guest, name='trailer_guest'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        {% block meta %}
        {% endblock meta %}
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    </head>

    <body>
        {% block content %}
        {% endblock content %}
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </body>
</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pacilflix Navbar</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .navbar-custom {
            background-color: #000; 
        }

        .navbar-custom .navbar-brand {
            color: #fff;
            font-weight: bold;
            font-size: 24px;
            transition: color 0.3s; /* Animasi perubahan warna */
        }

        .navbar-custom .navbar-brand:hover {
            color: #e50914; /* Warna merah saat dihover */
        }

        .navbar-custom .navbar-nav .nav-link {
            color: #fff !important; 
        }

        .navbar-custom .navbar-toggler {
            border-color: #fff; 
        }

        .navbar-custom .navbar-toggler-icon {
            background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='%23fff' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3Csv/svg>");
        }

        .navbar-custom .navbar-nav .nav-link:hover {
            color: #e50914 !important; 
        }
    </style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-custom">
    <a class="navbar-brand" href="#">P A C I L F L I X</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tayangan:tayangan' %}">Daftar Tayangan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'langganan:daftar_kontributor' %}">Daftar Kontributor</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'daftar_favorit:show_favorite' %}">Daftar Favorit</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'daftar_unduhan:show_downloads' %}">Daftar Unduhan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'langganan:langganan' %}">Kelola Langganan</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'authentication:logout' %}">Logout
                </a>
            </li>
        </ul>
    </div>
</nav>

<!-- Bootstrap JS and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

templates/navbar_guest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pacilflix Navbar Guest</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .navbar-custom {
            background-color: #000; 
        }

        .navbar-custom .navbar-brand {
            color: #fff;
            font-weight: bold;
            font-size: 24px;
            transition: color 0.3s; /* Animasi perubahan warna */
        }

        .navbar-custom .navbar-brand:hover {
            color: #e50914; /* Warna merah saat dihover */
        }

        .navbar-custom .navbar-nav .nav-link {
            color: #fff !important; 
        }

        .navbar-custom .navbar-toggler {
            border-color: #fff; 
        }

        .navbar-custom .navbar-toggler-icon {
            background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='%23fff' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3Csv/svg>");
        }

        .navbar-custom .navbar-nav .nav-link:hover {
            color: #e50914 !important; 
        }
    </style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-custom">
    <a class="navbar-brand" href="#">P A C I L F L I X</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'trailer:trailer_guest' %}">Trailer Tayangan</a>
            </li>
        </ul>
    </div>
</nav>

<!-- Bootstrap JS and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>