main/urls.py
from django.urls import path
from main.views import show_main

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
]

pacilflix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('', include('main.urls')),
    path('', include('authentication.urls')),
    path('admin/', admin.site.urls),
    path('tayangan/', include('tayangan.urls')),
    path('trailer/', include('trailer.urls')),
    path('ulasan/', include('ulasan.urls')),
    path('langganan/', include('langganan.urls')),
    path('daftar_favorit/', include('daftar_favorit.urls', namespace='daftar_favorit')),
    path('daftar_unduhan/', include('daftar_unduhan.urls', namespace='daftar_unduhan')),
]

tayangan/urls.py
# from tayangan.views import show_tayangan # Hapus baris ini atau komentari
from django.urls import path
from django.views.generic import TemplateView
from .views import *

app_name = 'tayangan'

urlpatterns = [
    path('series/episode/<series_id>/<episode_number>/', episode, name='episode'),
    path('film/<film_id>/', film, name='film'),
    path('series/<series_id>/', series, name='series'),
    path('', tayangan, name='tayangan'),
    path('unduh_tayangan/<str:id_tayangan>/', unduh_tayangan, name='unduh_tayangan'),
    path('unduh_tayangan_series/<str:id_tayangan>/', unduh_tayangan_series, name='unduh_tayangan_series'),
    path('insert_favorit_film/<str:id_tayangan>', tambah_ke_daftar_favorit, name='insert_favorit'),
    path('insert_favorit_series/<str:id_series>/<str:judul>/', daftar_favorit_series, name='insert_favorit_series'),
    path('add_tonton/', add_tonton, name='add_tonton'),
    path('ulasan/<tayangan_id>', open_ulasan, name='open_ulasan'),
    path('search/', show_hasil_pencarian_tayangan, name='hasil_search'),
]

ulasan/urls.py
from django.urls import path
from .views import *

app_name = 'ulasan'

urlpatterns = [
    path('<id_tayangan>/', ulasan, name='ulasan'),
]

tayangan/views.py
import random
from urllib.parse import quote
import urllib.parse
from django.shortcuts import render, redirect
from django.db import connection
from django.contrib.auth.decorators import login_required
from django.http import *
from datetime import *
from django.core.paginator import Paginator


def execute_query(query):
    with connection.cursor() as cursor:
        cursor.execute(query)
        columns = [col[0] for col in cursor.description]
        return [
            dict(zip(columns, row))
            for row in cursor.fetchall()
        ]

#Fungsi untuk mengurus halaman film, akan mereturn html film
def film(request, film_id):
    with connection.cursor() as cursor:
        cursor.execute(
            f"SELECT judul, sinopsis, asal_negara FROM TAYANGAN WHERE id = '{film_id}'"
        )
        film_details = cursor.fetchone()

        if film_details:
            cursor.execute(
                f"SELECT genre FROM GENRE_TAYANGAN WHERE id_tayangan = '{film_id}'"
            )
            genres = [genre[0] for genre in cursor.fetchall()]

            cursor.execute(
                f"SELECT url_video_film, release_date_film, durasi_film FROM FILM WHERE id_tayangan = '{film_id}'"
            )
            film_info = cursor.fetchone()

            cursor.execute(
                f"SELECT id_sutradara FROM TAYANGAN WHERE id = '{film_id}'"
            )
            director_id = cursor.fetchone()[0] if cursor.rowcount > 0 else None

            director = None
            if director_id:
                cursor.execute(
                    f"SELECT nama FROM CONTRIBUTORS WHERE id = '{director_id}'"
                )
                director = cursor.fetchone()[0]

            cursor.execute(
                f"SELECT id_pemain FROM MEMAINKAN_TAYANGAN WHERE id_tayangan = '{film_id}'"
            )
            pemain_ids = cursor.fetchall()

            pemain_names = []
            for pemain_id in pemain_ids:
                cursor.execute(
                    f"SELECT nama FROM CONTRIBUTORS WHERE id = '{pemain_id[0]}'"
                )
                pemain_name = cursor.fetchone()
                if pemain_name:
                    pemain_names.append(pemain_name[0])

            pemain = pemain_names if pemain_names else None

            cursor.execute(
                f"SELECT id_penulis_skenario FROM MENULIS_SKENARIO_TAYANGAN WHERE id_tayangan = '{film_id}'"
            )
            penulis_ids = cursor.fetchall()

            penulis_names = []
            for penulis_id in penulis_ids:
                cursor.execute(
                    f"SELECT nama FROM CONTRIBUTORS WHERE id = '{penulis_id[0]}'"
                )
                penulis_name = cursor.fetchone()
                if penulis_name:
                    penulis_names.append(penulis_name[0])

            penulis = penulis_names if penulis_names else None
            release_date_film = film_info[1]  # This is already a datetime.date object
            is_released = release_date_film <= datetime.now().date()

            film_details = {
                'judul': film_details[0],
                'sinopsis': film_details[1],
                'asal_negara': film_details[2],
                'genres': genres,
                'is_released': is_released,
                'url_video_film' : film_info[0],
                'release_date_film': film_info[1],
                'durasi_film': film_info[2],
                'sutradara': director,
                'pemain' : pemain,
                'penulis' : penulis,
                'id_tayangan' : film_id
            }

    return render(request, 'hal_film.html', {'film_details': film_details})

#Fungsi untuk mengurus halaman series, akan mereturn html series
def series(request, series_id):
    with connection.cursor() as cursor:
        cursor.execute(
            f"SELECT judul, sinopsis, asal_negara FROM TAYANGAN WHERE id = '{series_id}'"
        )
        series_details = cursor.fetchone()

        if series_details:
            cursor.execute(
                f"SELECT genre FROM GENRE_TAYANGAN WHERE id_tayangan = '{series_id}'"
            )
            genres = [genre[0] for genre in cursor.fetchall()]

            cursor.execute(
                f"SELECT id_sutradara FROM TAYANGAN WHERE id = '{series_id}'"
            )
            director_id = cursor.fetchone()[0] if cursor.rowcount > 0 else None

            director = None
            if director_id:
                cursor.execute(
                    f"SELECT nama FROM CONTRIBUTORS WHERE id = '{director_id}'"
                )
                director = cursor.fetchone()[0]

            cursor.execute(
                f"SELECT id_pemain FROM MEMAINKAN_TAYANGAN WHERE id_tayangan = '{series_id}'"
            )
            pemain_ids = cursor.fetchall()
            pemain_names = []
            for pemain_id in pemain_ids:
                cursor.execute(
                    f"SELECT nama FROM CONTRIBUTORS WHERE id = '{pemain_id[0]}'"
                )
                pemain_name = cursor.fetchone()
                if pemain_name:
                    pemain_names.append(pemain_name[0])
            pemain = pemain_names if pemain_names else None

            cursor.execute(
                f"SELECT id_penulis_skenario FROM MENULIS_SKENARIO_TAYANGAN WHERE id_tayangan = '{series_id}'"
            )
            penulis_ids = cursor.fetchall()
            penulis_names = []
            for penulis_id in penulis_ids:
                cursor.execute(
                    f"SELECT nama FROM CONTRIBUTORS WHERE id = '{penulis_id[0]}'"
                )
                penulis_name = cursor.fetchone()
                if penulis_name:
                    penulis_names.append(penulis_name[0])
            penulis = penulis_names if penulis_names else None

            # Mendapatkan detail episode
            cursor.execute(f"""SELECT id_series, sub_judul
                               FROM EPISODE
                               WHERE id_series = '{series_id}';""")
            episodes_data = cursor.fetchall()
            episodes_num = [(i, *episode) for i, episode in enumerate(episodes_data)]

            series_details = {
                'judul': series_details[0],
                'sinopsis': series_details[1],
                'asal_negara': series_details[2],
                'genres': genres,
                'sutradara': director,
                'pemain' : pemain,
                'penulis' : penulis,
                'id_tayangan' : series_id,
                'episodes' : episodes_num,
            }

            return render(request, 'hal_series.html', {'series_details': series_details})
        else:
            # Handle case when series_details is not found
            # For example, return an error page or redirect to another page
            return HttpResponse("Series not found", status=404)

def episode(request, series_id, episode_number):
    episode_number = int(episode_number)
    with connection.cursor() as cursor:
        # Mendapatkan judul tayangan
        cursor.execute("SELECT judul FROM TAYANGAN WHERE id = %s", [series_id])
        series_title = cursor.fetchone()

        # Mendapatkan semua episode untuk id_series tertentu
        cursor.execute("SELECT * FROM EPISODE WHERE id_series = %s", [series_id])
        episodes = cursor.fetchall()
        episodes_num = [(i, *episode) for i, episode in enumerate(episodes)]


        # Memilih episode berdasarkan episode_number
        if 0 <= episode_number < len(episodes):
            episode = episodes[episode_number]
            episode_details = {
                'id_series': episode[0],
                'sub_judul': episode[1],
                'sinopsis': episode[2],
                'durasi': episode[3],
                'url_video': episode[4],
                'release_date': episode[5],
                'is_released': episode[5] <= datetime.now().date(),}

        else:
            episode_details = None

    context = {
        'episodes': episodes_num,
        'episode': episode_details,
        'series_title': series_title[0] if series_title else None,  # Ensure series_title is not None before accessing the title
    }
    return render(request, 'hal_eps.html', context)

def tayangan(request):

    top_10_query = f"""
        WITH durasi_tayangan AS (
            SELECT T.id AS id, F.durasi_film AS durasi
            FROM TAYANGAN AS T
            JOIN FILM AS F ON F.id_tayangan = T.id
            UNION
            SELECT T.id AS id, AVG(E.durasi) AS durasi
            FROM TAYANGAN AS T
            JOIN SERIES AS S ON S.id_tayangan = T.id
            JOIN EPISODE AS E ON E.id_series = T.id
            GROUP BY T.id
        ), recent_views AS (
            SELECT T.id AS id, EXTRACT(EPOCH FROM (RW.end_date_time - RW.start_date_time)) / 60 AS watch_time
            FROM TAYANGAN AS T
            JOIN RIWAYAT_NONTON AS RW ON RW.id_tayangan = T.id
            WHERE RW.start_date_time >= NOW() - INTERVAL '7 DAYS'
        )
        SELECT T.id, T.judul, T.sinopsis_trailer, T.url_video_trailer, T.release_date_trailer, COUNT(RV.id) as total_view,
               CASE
                   WHEN EXISTS (SELECT 1 FROM FILM AS F WHERE F.id_tayangan = T.id) THEN 'film'
                   ELSE 'series'
               END AS tipe_tayangan
        FROM TAYANGAN AS T
        JOIN durasi_tayangan AS DT ON DT.id = T.id
        JOIN recent_views AS RV ON RV.id = T.id
        WHERE RV.watch_time > (0.7 * DT.durasi)
        GROUP BY T.id, T.judul, T.sinopsis_trailer, T.url_video_trailer, T.release_date_trailer
        ORDER BY total_view DESC, T.judul ASC
        LIMIT 10;
    """

    film_query = f"""
        SELECT T.id, T.judul, T.sinopsis_trailer, T.url_video_trailer, T.release_date_trailer
        FROM TAYANGAN AS T
        JOIN FILM AS F ON F.id_tayangan = T.id;
    """

    series_query = f"""
        SELECT T.id, T.judul, T.sinopsis_trailer, T.url_video_trailer, T.release_date_trailer

tayangan/templates/daftar_tayangan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tayangan</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap');

        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
            background: linear-gradient(to bottom, #bb301a, #ed7e59);
            font-family: 'Lato', sans-serif;
        }
        .container {
            margin-top: 50px;
        }

        .search-bar {
            margin-bottom: 20px;
        }
        .button-custom {
            background-color: rgba(28, 15, 15, 0.569);
            color: white;
            border: none;
            padding: 10px 20px;
            margin: 5px 0;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }
        h1, h2 {
            color: white;
        }

        .search-input {
            width: 50%;
            padding: 10px;
            border-radius: 5px;
            border: 1px solid #ddd;
        }
        .search-button {
            padding: 10px 20px;
            border-radius: 20px;
            background-color: white;
            color: black;
            border: 1px solid #ddd;
            cursor: pointer;
            font-size: 16px;
        }
        table {
            width: 100%;
            background-color: #fff;
            color: #54362d;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 10px;
            text-align: left;
        }
    </style>
</head>
{% endblock meta %}

{% block content %}
<body>
{% include 'navbar.html' %}

<div class="container">
    <h1 class="text-center mb-4">Tayangan</h1>

    <form action="{% url 'tayangan:hasil_search' %}" method="get" class="input-group mb-3 search-bar">
        <input id="searchBar" name="value" type="text" class="form-control search-input" placeholder="Search..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
            <button class="btn search-button" type="submit">Search</button>
        </div>
    </form>

    <h2 class="mb-3">Top 10 Global Watchlist</h2>
    <table>
        <thead>
        <tr>
            <th>Peringkat</th>
            <th>Judul</th>
            <th>Sinopsis Trailer</th>
            <th>URL Trailer</th>
            <th>Tanggal Rilis Trailer</th>
            <th>Total View (7 Hari Terakhir)</th>
            <th>Tayangan</th>
        </tr>
        </thead>
        <tbody>
        {% for item in top_10 %}
        <tr>
            <td>{{ item.rank }}</td>
            <td>{{ item.judul }}</td>
            <td>{{ item.sinopsis_trailer }}</td>
            <td><a href="{{ item.url_video_trailer }}">Lihat trailer</a></td>
            <td>{{ item.release_date_trailer }}</td>
            <td>{{ item.total_view }}</td>
            <td><a href="{% url 'tayangan:'|add:item.tipe_tayangan item.id %}">Lihat tayangan</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    <h2 class="mt-5 mb-3">Film</h2>
    <table>
        <thead>
        <tr>
            <th>Judul</th>
            <th>Sinopsis</th>
            <th>URL Trailer</th>
            <th>Tanggal Rilis</th>
            <th>Tayangan</th>
        </tr>
        </thead>
        <tbody>
        {% for film in film %}
        <tr>
            <td>{{ film.judul }}</td>
            <td>{{ film.sinopsis_trailer }}</td>
            <td><a href="{{ film.url_video_trailer }}">Lihat trailer</a></td>
            <td>{{ film.release_date_trailer }}</td>
            <td><a href="{% url 'tayangan:film' film.id %}">Lihat tayangan</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    <h2 class="mt-5 mb-3">Series</h2>
    <table>
        <thead>
        <tr>
            <th>Judul</th>
            <th>Sinopsis</th>
            <th>Trailer</th>
            <th>URL Trailer</th>
            <th>Tanggal Rilis</th>
            <th>Tayangan</th>
        </tr>
        </thead>
        <tbody>
        {% for series in series %}
        <tr>
            <td>{{ series.judul }}</td>
            <td>{{ series.sinopsis_trailer }}</td>
            <td><a href="{{ series.url_video_trailer }}">Lihat trailer</a></td>
            <td>{{ series.release_date_trailer }}</td>
            <td><a href="{% url 'tayangan:series' series.id %}">Lihat tayangan</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</body>
{% endblock content %}

tayangan/templates/hal_eps.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar.html' %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap');

    body {
        font-family: 'Lato', sans-serif;
        background: linear-gradient(to bottom, #bb301a, #ed7e59);
    }

    .container {
        width: 80%;
        margin: auto;
        padding-top: 20px;
        color: #202021;
        background-color: #f3c7b9;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 8px 16px rgba(0,0,0,0.25);
    }

    .section {
        background-color: #fce9e4;
        padding: 15px;
        border-radius: 5px;
        margin-bottom: 20px;
        box-shadow: 0 4px 8px rgba(0,0,0,0.15);
    }

    h1, h2, h3 {
        color: #1c1d1d;
    }

    p, li {
        color: #2c2c2c;
    }

    .button {
        padding: 10px 20px;
        border-radius: 5px;
        background-color: #54362d;
        color: #fff7f5;
        border: none;
        cursor: pointer;
        font-size: 16px;
        margin-top: 10px;
        display: inline-block;
    }

    ul {
        padding: 0;
        list-style-type: none;
    }

    li {
        padding: 5px 0;
    }

    a {
        color: #54362d;
        text-decoration: none;
    }

    a:hover {
        text-decoration: underline;
    }


    .btn-custom {
        background-color: #54362d;
        color: white;
        border: none;
        border-radius: 20px; /* membuat tombol ujungnya oval */
        padding: 10px 20px;
        cursor: pointer;
        font-weight: bold; /* teksnya menjadi tebal */
        margin-bottom: 10px;
    }

    .btn-custom:hover {
        background-color: #6c4a3c; /* ubah warna saat tombol dihover */
    }
</style>

<div class="container">
    <h1>Judul: {{ series_title }}</h1>

    <div class="section">
        {% if episode.is_released %}
        <form id="tontonForm">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{ episode_details.id_series }}">
            <input type="hidden" name="tipe" value="series">
            <label for="progress">Progress Tontonan (0-100):</label>
            <input type="number" id="progress" name="progress" min="0" max="100" required>
            <input type="hidden" name="durasi" value="{{ episode_details.durasi }}">
            <button class="button" type="button" onclick="submitTontonForm()">Tonton</button>
        </form>
        {% endif %}

    </div>
    {% if episode %}
    <h2>Sub Judul: {{ episode.sub_judul }}</h2>
    <div class="section">
        <h3>Sinopsis Episode:</h3>
        <p>{{ episode.sinopsis }}</p>
    </div>
    <div class="section">
        <p><strong>Durasi Episode:</strong> {{ episode.durasi }}</p>
        <p><strong>Tanggal Rilis Episode:</strong> {{ episode.release_date }}</p>
        <p><strong>URL Episode:</strong> <a href="{{ episode.url_video }}">Watch Episode</a></p>
        <!-- Tombol Tonton hanya ditampilkan jika episode sudah dirilis -->
        {% if episode.release_date <= 'today'|date:"Y-m-d" %}
        <form method="POST" action="{% url 'add_tonton' %}">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{ episode.id }}">
            <input type="hidden" name="tipe" value="episode">
            <label for="progress">Progress Tontonan (0-100):</label>
            <input type="number" id="progres" name="progress" min="0" max="100" required>
            <input type="hidden" name="durasi" value="{{ episode.durasi }}">
            <button class="button" type="submit">Tonton</button>
        </form>
        {% endif %}
    </div>
    {% else %}
    <p>Episode tidak ditemukan.</p>
    {% endif %}

    <div class="section">
        <h3>Episode Lainnya:</h3>
        <ul>
            {% for episode in episodes %}
            <li>
                <a href="{% url 'tayangan:episode' episode.1 episode.0 %}">
                    <button class="btn-custom">Episode {{ episode.0|add:1 }}</button>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

<script>
    function submitTontonForm() {
        const form = document.getElementById('tontonForm');
        const formData = new FormData(form);

        fetch("{% url 'tayangan:add_tonton' %}", {
            method: "POST",
            body: formData,
            headers: {
                "X-Requested-With": "XMLHttpRequest"
            },
        })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    alert('Tontonan berhasil ditambahkan!');
                    // Optionally, update the UI to reflect the changes
                } else {
                    alert(data.error);
                }
            })
            .catch(error => {
                console.error('There was an error:', error);
            });
    }
</script>
{% endblock content %}

tayangan/templates/hal_film.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Film Page</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap');
        body {
            font-family: 'Lato', sans-serif;
            background: linear-gradient(to bottom, #bb301a, #ed7e59);
            color: #1c1d1d;
            margin: 0;
            padding: 0;
        }
        .container {
            width: 80%;
            margin: auto;
            padding: 20px;
            background-color: #f3c7b9;
            border-radius: 10px;
            box-shadow: 0 8px 16px rgba(0,0,0,0.25);
        }
        .section {
            background-color: #fce9e4;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
            box-shadow: 0 4px 8px rgba(0,0,0,0.15);
        }
        h1, h2, p, li {
            margin-bottom: 10px;
        }
        p, li {
            color: #2c2c2c;
        }
        a {
            color: #54362d;
            text-decoration: none;
        }
        .button {
            padding: 10px 20px;
            margin-top: 10px;
            margin-right: 10px;
            background-color: #54362d;
            color: #fff7f5;
            border-radius: 5px;
            border: none;
            cursor: pointer;
            font-size: 16px;
            display: inline-block;
        }
        .modal-content {
            background-color: #fce9e4; /* Sesuaikan dengan tema */
            color: #1c1d1d;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0,0,0,0.15);
        }
        .film-reviews a {
            padding: 10px 20px;
            cursor: pointer;
            border: none;
            border-radius: 5px;
            background-color: #28a745;
            color: #fff;
        }
        ul, li {
            list-style-type: none;
            padding: 0;
        }
    </style>
</head>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="container">
    <div class="section">
        <h1>{{ film_details.judul }}</h1>
        <div class="section">
            {% if film_details.is_released %}
            <form id="tontonForm">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ film_details.id_tayangan }}">
                <input type="hidden" name="tipe" value="film">
                <label for="progress">Progress Tontonan (0-100):</label>
                <input type="number" id="progress" name="progress" min="0" max="100" required>
                <input type="hidden" name="durasi" value="{{ film_details.durasi_film }}">
                <button class="button" type="button" onclick="submitTontonForm()">Tonton</button>
            </form>
            {% endif %}

            <div class="section">
                <a href="{% url 'tayangan:unduh_tayangan' film_details.id_tayangan %}">
                    <button type="button" class="btn btn-primary" id="btnUnduh" data-id="{{ series_details.id_tayangan }}">Unduh</button>
                </a>
                <button class="btn btn-primary mb-2" id="btnFavorit" data-bs-toggle="modal" data-bs-target="#favoriteListModal">Favorit Tayangan</button>
                <a href="{% url 'tayangan:insert_favorit' film_details.id_tayangan %}" class="button">Ulasan</a>
            </div>

            <p>{{ film_details.sinopsis }}</p>
            <p>Tanggal Rilis: {{ film_details.release_date_film }}</p>
            <p>Genre:
            {% for genre in film_details.genres %}
            {{ genre }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
            </p>
            <p>Asal Negara: {{ film_details.asal_negara }}</p>
            <p>Durasi: {{ film_details.durasi_film }} mins</p>
            <p>Pemain:
            {% for pemain in film_details.pemain %}
            {{ pemain }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
            </p>
            <p>Penulis Skenario:
            {% for penulis in film_details.penulis %}
            {{ penulis }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
            </p>
            <p>Sutradara: {{ film_details.sutradara }}</p>
        </div>

        <div class="film-reviews">
            <a href="{% url 'ulasan:ulasan' film_details.id_tayangan %}" class="button">Ulasan</a>
        </div>
    </div>
</div>

<script>
    function submitTontonForm() {
        const form = document.getElementById('tontonForm');
        const formData = new FormData(form);

        fetch("{% url 'tayangan:add_tonton' %}", {
            method: "POST",
            body: formData,
            headers: {
                "X-Requested-With": "XMLHttpRequest"
            },
        })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    alert('Tontonan berhasil ditambahkan!');
                    // Optionally, update the UI to reflect the changes
                } else {
                    alert(data.error);
                }
            })
            .catch(error => {
                console.error('There was an error:', error);
            });
    }
</script>

{% endblock %}